--- # Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epc-msc
  namespace: msc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epc-msc
  template:
    metadata:
      labels:
        app: epc-msc
    spec:
      containers:
      - name: epc-msc
        image: k3d-registry.localhost:5000/osmosys-msc
        env:
        - name: OSMOHLR_FQDN
          value: epc-hlr-svc.hlr-ns.cluster.local
        volumeMounts:
        - name: config
          mountPath: /etc/osmocom/config/osmo-msc.cfg
          subPath: osmo-msc.cfg
        ports:
        - name: sctp-port
          containerPort: 29118
          protocol: SCTP
        - name: tcp-port
          containerPort: 2775
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: epc-msc-cm

--- # Service

apiVersion: v1
kind: Service
metadata:
  name: epc-msc-svc
  namespace: msc-ns
spec:
  selector:
    app: epc-msc
  ports:
  - name: sctp-port
    port: 29118
    targetPort: 29118
    protocol: SCTP
  - name: tcp-port
    port: 2775
    targetPort: 2775

--- # ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: epc-msc-cm
  namespace: msc-ns
data:   
  osmo-msc.cfg: |
    line vty
     no login
     bind 127.0.0.1
    ctrl
     bind 127.0.0.1
    network
     network country code 001
     mobile network code 01
     short name OsmoMSC
     long name OsmoMSC
     encryption a5 0
     rrlp mode none
     mm info 1
    msc
     assign-tmsi
     auth-tuple-max-reuse-count 3
     auth-tuple-reuse-on-error 1
    sgs
     local-ip 127.0.0.1
     local-port 29118
     vlr-name vlr.mnc001.mcc001.3gppnetwork.org
    hlr
     remote-ip OSMOHLR_IP
     remote-port 4222
    smpp
     local-tcp-ip 127.0.0.1 2775
     policy accept-all
     smpp-first
