--- # Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epc-hlr
  namespace: hlr-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epc-hlr
  template:
    metadata:
      labels:
        app: epc-hlr
    spec:
      containers:
      - name: epc-hlr
        image: k3d-registry.localhost:5000/osmosys-hlr
        volumeMounts:
        - name: config
          mountPath: /etc/osmocom/osmo-hlr.cfg
          subPath: osmo-hlr.cfg
        ports:
        - name: tcp-port
          containerPort: 4222
      volumes:
      - name: config
        configMap:
          name: epc-hlr-cm

--- # Service

apiVersion: v1
kind: Service
metadata:
  name: epc-hlr-svc
  namespace: hlr-ns
spec:
  selector:
    app: epc-hlr
  ports:
  - name: tcp-port
    port: 4222
    targetPort: 4222

--- # ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: epc-hlr-cm
  namespace: hlr-ns
data:   
  osmo-hlr.cfg: |
    log stderr
     logging filter all 1
     logging color 1
     logging print category 1
     logging timestamp 1
     logging print extended-timestamp 1
     logging level all debug
     logging level linp error
    !
    line vty
     no login
     bind 127.0.0.1
    ctrl
     bind 127.0.0.1
    hlr
     gsup
      bind ip 127.0.0.1